apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8080
      name: backend
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/no-waste-app/no-waste/backend
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /v2/api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
