stages:
    - build
    - test
build: 
    stage: build
    image: node:12
    script:
        - echo "Building UI app"
        - cd ui
        - yarn install
        - yarn build
test:
    stage: test
    image: node:12
    script:
        - echo "Testing"
        - cd ui
        - yarn install
        - yarn test
