apiVersion: v1
kind: Service
metadata:
  name: backend-mock
  labels:
    app: backend-mock
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8080
      name: backend-mock
  selector:
    app: backend-mock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mock
  labels:
    app: backend-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-mock
  template:
    metadata:
      labels:
        app: backend-mock
    spec:
      containers:
        - name: backend-mock
          image: ghcr.io/no-waste-app/no-waste/backend-mock:0722mt2
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-mock
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-mock
                port:
                  number: 80
