name: Build and Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build_deploy_image:
    name: Build and Deploy Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: 'build_deploy_image'

#       - name: Extract cache
#         uses: actions/cache@v2
#         with:
#           path: ~/.skaffold/cache
#           key: ${{ runner.os }}-skaffold-1.13.0
#           restore-keys: ${{ runner.os }}-skaffold-
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Add Kube config
        run: |
          mkdir -p /home/runner/.kube
          echo "$KUBECONFIG" > /home/runner/.kube/config
        shell: bash
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Install skaffold
        uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.20.0'

      - name: Build and Deploy
        run: |
          set -x
          skaffold run

      - name: Check deployed app
        run: kubectl get deployments
